version: '3'
services:
  app:
    ports:
      - 8000:8000
      - 8081:8081
    container_name: "app_go"
    tty: true
    build: . # read Dockerfile in current directory
    volumes:
      - ./host_go/:/go/

